include:
  - board: nice_nano_v2
    shield: cradio_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sweep_left

  - board: nice_nano_v2
    shield: cradio_right
    artifact-name: sweep_right

  - board: nice_nano_v2
    shield: settings_reset
