include:
  - board: nice_nano_v2
    shield: cradio_left
    artifact-name: sweep_left

  - board: nice_nano_v2
    shield: cradio_right
    artifact-name: sweep_right

  # - board: nice_nano_v2
  #   shield: settings_reset
  #   artifact-name: settings_reset
